/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../../../../common";

export interface InternalInterface extends utils.Interface {
  functions: {
    "GAS_PRICE_BITS()": FunctionFragment;
    "MESSAGE_FIXED_BYTES()": FunctionFragment;
    "MESSAGE_FIXED_BYTES_PER_TOKEN()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "GAS_PRICE_BITS"
      | "MESSAGE_FIXED_BYTES"
      | "MESSAGE_FIXED_BYTES_PER_TOKEN"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "GAS_PRICE_BITS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MESSAGE_FIXED_BYTES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MESSAGE_FIXED_BYTES_PER_TOKEN",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "GAS_PRICE_BITS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MESSAGE_FIXED_BYTES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MESSAGE_FIXED_BYTES_PER_TOKEN",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Internal extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InternalInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    GAS_PRICE_BITS(overrides?: CallOverrides): Promise<[number]>;

    MESSAGE_FIXED_BYTES(overrides?: CallOverrides): Promise<[BigNumber]>;

    MESSAGE_FIXED_BYTES_PER_TOKEN(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  GAS_PRICE_BITS(overrides?: CallOverrides): Promise<number>;

  MESSAGE_FIXED_BYTES(overrides?: CallOverrides): Promise<BigNumber>;

  MESSAGE_FIXED_BYTES_PER_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    GAS_PRICE_BITS(overrides?: CallOverrides): Promise<number>;

    MESSAGE_FIXED_BYTES(overrides?: CallOverrides): Promise<BigNumber>;

    MESSAGE_FIXED_BYTES_PER_TOKEN(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    GAS_PRICE_BITS(overrides?: CallOverrides): Promise<BigNumber>;

    MESSAGE_FIXED_BYTES(overrides?: CallOverrides): Promise<BigNumber>;

    MESSAGE_FIXED_BYTES_PER_TOKEN(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    GAS_PRICE_BITS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MESSAGE_FIXED_BYTES(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MESSAGE_FIXED_BYTES_PER_TOKEN(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
