/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../common";

export declare namespace IRMN {
  export type TaggedRootStruct = { commitStore: AddressLike; root: BytesLike };

  export type TaggedRootStructOutput = [commitStore: string, root: string] & {
    commitStore: string;
    root: string;
  };
}

export interface IRMNInterface extends Interface {
  getFunction(
    nameOrSignature: "isBlessed" | "isCursed(bytes16)" | "isCursed()"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isBlessed",
    values: [IRMN.TaggedRootStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isCursed(bytes16)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCursed()",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "isBlessed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCursed(bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isCursed()", data: BytesLike): Result;
}

export interface IRMN extends BaseContract {
  connect(runner?: ContractRunner | null): IRMN;
  waitForDeployment(): Promise<this>;

  interface: IRMNInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isBlessed: TypedContractMethod<
    [taggedRoot: IRMN.TaggedRootStruct],
    [boolean],
    "view"
  >;

  "isCursed(bytes16)": TypedContractMethod<
    [subject: BytesLike],
    [boolean],
    "view"
  >;

  "isCursed()": TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isBlessed"
  ): TypedContractMethod<
    [taggedRoot: IRMN.TaggedRootStruct],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCursed(bytes16)"
  ): TypedContractMethod<[subject: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isCursed()"
  ): TypedContractMethod<[], [boolean], "view">;

  filters: {};
}
