/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../../common";
import type {
  CallWithExactGas,
  CallWithExactGasInterface,
} from "../../../../../../../@chainlink/contracts-ccip/src/v0.8/shared/call/CallWithExactGas";

const _abi = [
  {
    inputs: [],
    name: "NoContract",
    type: "error",
  },
  {
    inputs: [],
    name: "NoGasForCallExactCheck",
    type: "error",
  },
  {
    inputs: [],
    name: "NotEnoughGasForCall",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212201f972b5d4060dd995e715b08bcab58d35037b73ad2d9a02901d68e6c592ee12164736f6c63430008130033";

type CallWithExactGasConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CallWithExactGasConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CallWithExactGas__factory extends ContractFactory {
  constructor(...args: CallWithExactGasConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CallWithExactGas & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CallWithExactGas__factory {
    return super.connect(runner) as CallWithExactGas__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CallWithExactGasInterface {
    return new Interface(_abi) as CallWithExactGasInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CallWithExactGas {
    return new Contract(address, _abi, runner) as unknown as CallWithExactGas;
  }
}
