/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConfirmedOwner } from "./ConfirmedOwner";
export type { ConfirmedOwnerWithProposal } from "./ConfirmedOwnerWithProposal";
export type { OwnerIsCreator } from "./OwnerIsCreator";
