/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC677Receiver,
  IERC677ReceiverInterface,
} from "../../../../../../../@chainlink/contracts-ccip/src/v0.8/shared/interfaces/IERC677Receiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onTokenTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC677Receiver__factory {
  static readonly abi = _abi;
  static createInterface(): IERC677ReceiverInterface {
    return new Interface(_abi) as IERC677ReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC677Receiver {
    return new Contract(address, _abi, runner) as unknown as IERC677Receiver;
  }
}
