/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  Client,
  ClientInterface,
} from "../../../../../@chainlink/contracts-ccip/contracts/libraries/Client";

const _abi = [
  {
    inputs: [],
    name: "EVM_EXTRA_ARGS_V1_TAG",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GENERIC_EXTRA_ARGS_V2_TAG",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SVM_ACCOUNT_BYTE_SIZE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SVM_EXTRA_ARGS_MAX_ACCOUNTS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SVM_EXTRA_ARGS_V1_TAG",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SVM_MESSAGING_ACCOUNTS_OVERHEAD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SVM_TOKEN_TRANSFER_DATA_OVERHEAD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x610254610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100875760003560e01c806371953f601161006557806371953f60146100e65780637498e355146101045780639713cbbd14610122578063a5dd87d81461014057610087565b80631ac428f81461008c5780633ab8c0d0146100aa5780635dd8ee3e146100c8575b600080fd5b61009461015e565b6040516100a191906101ad565b60405180910390f35b6100b2610163565b6040516100bf9190610203565b60405180910390f35b6100d061016e565b6040516100dd91906101ad565b60405180910390f35b6100ee610173565b6040516100fb91906101ad565b60405180910390f35b61010c610178565b6040516101199190610203565b60405180910390f35b61012a610183565b60405161013791906101ad565b60405180910390f35b610148610189565b6040516101559190610203565b60405180910390f35b604081565b6397a657c960e01b81565b600281565b602081565b63181dcf1060e01b81565b61012c81565b631f3b3aba60e01b81565b6000819050919050565b6101a781610194565b82525050565b60006020820190506101c2600083018461019e565b92915050565b60007fffffffff0000000000000000000000000000000000000000000000000000000082169050919050565b6101fd816101c8565b82525050565b600060208201905061021860008301846101f4565b9291505056fea26469706673582212203f09ec0adc9e123fba77cd014d68fb0d99c9eb638c77e143862aaa7260f2eb0f64736f6c63430008180033";

type ClientConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ClientConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Client__factory extends ContractFactory {
  constructor(...args: ClientConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Client & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Client__factory {
    return super.connect(runner) as Client__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ClientInterface {
    return new Interface(_abi) as ClientInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Client {
    return new Contract(address, _abi, runner) as unknown as Client;
  }
}
