/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  Client,
  ClientInterface,
} from "../../../../../@chainlink/contracts-ccip/contracts/libraries/Client";

const _abi = [
  {
    inputs: [],
    name: "EVM_EXTRA_ARGS_V1_TAG",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GENERIC_EXTRA_ARGS_V2_TAG",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GENERIC_EXTRA_ARGS_V3_TAG",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SUI_ACCOUNT_BYTE_SIZE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SUI_EXTRA_ARGS_MAX_RECEIVER_OBJECT_IDS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SUI_EXTRA_ARGS_V1_TAG",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SUI_MESSAGING_ACCOUNTS_OVERHEAD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SUI_TOKEN_TRANSFER_DATA_OVERHEAD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SVM_ACCOUNT_BYTE_SIZE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SVM_EXTRA_ARGS_MAX_ACCOUNTS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SVM_EXTRA_ARGS_V1_TAG",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SVM_MESSAGING_ACCOUNTS_OVERHEAD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SVM_TOKEN_TRANSFER_DATA_OVERHEAD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x610385610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100d95760003560e01c806390c21ba611610096578063b5f958fc11610070578063b5f958fc146101ec578063bd62fad91461020a578063f736d63a14610228578063fe48911214610246576100d9565b806390c21ba6146101925780639713cbbd146101b0578063a5dd87d8146101ce576100d9565b80631ac428f8146100de57806335f92242146100fc5780633ab8c0d01461011a5780635dd8ee3e1461013857806371953f60146101565780637498e35514610174575b600080fd5b6100e6610264565b6040516100f391906102de565b60405180910390f35b610104610269565b6040516101119190610334565b60405180910390f35b610122610274565b60405161012f9190610334565b60405180910390f35b61014061027f565b60405161014d91906102de565b60405180910390f35b61015e610284565b60405161016b91906102de565b60405180910390f35b61017c610289565b6040516101899190610334565b60405180910390f35b61019a610294565b6040516101a79190610334565b60405180910390f35b6101b861029f565b6040516101c591906102de565b60405180910390f35b6101d66102a5565b6040516101e39190610334565b60405180910390f35b6101f46102b0565b60405161020191906102de565b60405180910390f35b6102126102b5565b60405161021f91906102de565b60405180910390f35b6102306102ba565b60405161023d91906102de565b60405180910390f35b61024e6102c0565b60405161025b91906102de565b60405180910390f35b604081565b63302326cb60e01b81565b6397a657c960e01b81565b600281565b602081565b63181dcf1060e01b81565b6321ea4ca960e01b81565b61012c81565b631f3b3aba60e01b81565b600181565b602081565b61010c81565b604081565b6000819050919050565b6102d8816102c5565b82525050565b60006020820190506102f360008301846102cf565b92915050565b60007fffffffff0000000000000000000000000000000000000000000000000000000082169050919050565b61032e816102f9565b82525050565b60006020820190506103496000830184610325565b9291505056fea2646970667358221220e5c312e5c6e14066cd41fa66ed1c8e4bda56422e69901cb1c44d32aabe2a470464736f6c63430008180033";

type ClientConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ClientConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Client__factory extends ContractFactory {
  constructor(...args: ClientConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Client & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Client__factory {
    return super.connect(runner) as Client__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ClientInterface {
    return new Interface(_abi) as ClientInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Client {
    return new Contract(address, _abi, runner) as unknown as Client;
  }
}
