/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  Pool,
  PoolInterface,
} from "../../../../../@chainlink/contracts-ccip/contracts/libraries/Pool";

const _abi = [
  {
    inputs: [],
    name: "CCIP_LOCK_OR_BURN_V1_RET_BYTES",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CCIP_POOL_V1",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CCIP_POOL_V1_RET_BYTES",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CCIP_POOL_V2",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6101f1610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100565760003560e01c80630ccb1dfe1461005b578063a894fde714610079578063b7f4192014610097578063cd30939a146100b5575b600080fd5b6100636100d3565b6040516100709190610112565b60405180910390f35b6100816100d8565b60405161008e9190610168565b60405180910390f35b61009f6100e3565b6040516100ac91906101a0565b60405180910390f35b6100bd6100e8565b6040516100ca9190610168565b60405180910390f35b602081565b63f208a58f60e01b81565b602081565b63aff2afbf60e01b81565b600063ffffffff82169050919050565b61010c816100f3565b82525050565b60006020820190506101276000830184610103565b92915050565b60007fffffffff0000000000000000000000000000000000000000000000000000000082169050919050565b6101628161012d565b82525050565b600060208201905061017d6000830184610159565b92915050565b600061ffff82169050919050565b61019a81610183565b82525050565b60006020820190506101b56000830184610191565b9291505056fea2646970667358221220cc5125aebc625682ea7a6eea07e5aacff511be16e258f3cde806e22619623ee264736f6c63430008180033";

type PoolConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PoolConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Pool__factory extends ContractFactory {
  constructor(...args: PoolConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Pool & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Pool__factory {
    return super.connect(runner) as Pool__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoolInterface {
    return new Interface(_abi) as PoolInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Pool {
    return new Contract(address, _abi, runner) as unknown as Pool;
  }
}
