/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as linkTokenSol from "./LinkToken.sol";
export type { linkTokenSol };
import type * as mockRouterSol from "./mockRouter.sol";
export type { mockRouterSol };
