/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOwner,
  IOwnerInterface,
} from "../../../../../@chainlink/contracts-ccip/contracts/interfaces/IOwner";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOwner__factory {
  static readonly abi = _abi;
  static createInterface(): IOwnerInterface {
    return new Interface(_abi) as IOwnerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IOwner {
    return new Contract(address, _abi, runner) as unknown as IOwner;
  }
}
