/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface InternalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "APTOS_PRECOMPILE_SPACE"
      | "CHAIN_FAMILY_SELECTOR_APTOS"
      | "CHAIN_FAMILY_SELECTOR_EVM"
      | "CHAIN_FAMILY_SELECTOR_SUI"
      | "CHAIN_FAMILY_SELECTOR_SVM"
      | "EVM_PRECOMPILE_SPACE"
      | "GAS_ESTIMATION_SENDER"
      | "GAS_PRICE_BITS"
      | "MESSAGE_FIXED_BYTES"
      | "MESSAGE_FIXED_BYTES_PER_TOKEN"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "APTOS_PRECOMPILE_SPACE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CHAIN_FAMILY_SELECTOR_APTOS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CHAIN_FAMILY_SELECTOR_EVM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CHAIN_FAMILY_SELECTOR_SUI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CHAIN_FAMILY_SELECTOR_SVM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVM_PRECOMPILE_SPACE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GAS_ESTIMATION_SENDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GAS_PRICE_BITS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MESSAGE_FIXED_BYTES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MESSAGE_FIXED_BYTES_PER_TOKEN",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "APTOS_PRECOMPILE_SPACE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CHAIN_FAMILY_SELECTOR_APTOS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CHAIN_FAMILY_SELECTOR_EVM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CHAIN_FAMILY_SELECTOR_SUI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CHAIN_FAMILY_SELECTOR_SVM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVM_PRECOMPILE_SPACE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GAS_ESTIMATION_SENDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GAS_PRICE_BITS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MESSAGE_FIXED_BYTES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MESSAGE_FIXED_BYTES_PER_TOKEN",
    data: BytesLike
  ): Result;
}

export interface Internal extends BaseContract {
  connect(runner?: ContractRunner | null): Internal;
  waitForDeployment(): Promise<this>;

  interface: InternalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  APTOS_PRECOMPILE_SPACE: TypedContractMethod<[], [bigint], "view">;

  CHAIN_FAMILY_SELECTOR_APTOS: TypedContractMethod<[], [string], "view">;

  CHAIN_FAMILY_SELECTOR_EVM: TypedContractMethod<[], [string], "view">;

  CHAIN_FAMILY_SELECTOR_SUI: TypedContractMethod<[], [string], "view">;

  CHAIN_FAMILY_SELECTOR_SVM: TypedContractMethod<[], [string], "view">;

  EVM_PRECOMPILE_SPACE: TypedContractMethod<[], [bigint], "view">;

  GAS_ESTIMATION_SENDER: TypedContractMethod<[], [string], "view">;

  GAS_PRICE_BITS: TypedContractMethod<[], [bigint], "view">;

  MESSAGE_FIXED_BYTES: TypedContractMethod<[], [bigint], "view">;

  MESSAGE_FIXED_BYTES_PER_TOKEN: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "APTOS_PRECOMPILE_SPACE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CHAIN_FAMILY_SELECTOR_APTOS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CHAIN_FAMILY_SELECTOR_EVM"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CHAIN_FAMILY_SELECTOR_SUI"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CHAIN_FAMILY_SELECTOR_SVM"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EVM_PRECOMPILE_SPACE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GAS_ESTIMATION_SENDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GAS_PRICE_BITS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MESSAGE_FIXED_BYTES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MESSAGE_FIXED_BYTES_PER_TOKEN"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
